### ISSUE TITLE
Problem on speedtest-cli

### ISSUE THREAD

**Issue by suportetikrn** [psylinux/internet_report#5]
## The script returned this error:

> > > > > > > > ```
> > > > > > > >             Generating Graphics                <<<<<<<<
> > > > > > > >               Wait a moment...                 <<<<<<<<
> > > > > > > > ```
> > > > > > > > ---

Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==0.3.4', 'console_scripts', 'speedtest-cli')()
  File "/usr/local/lib/python2.7/dist-packages/speedtest_cli.py", line 790, in main
    speedtest()
  File "/usr/local/lib/python2.7/dist-packages/speedtest_cli.py", line 644, in speedtest
    print_('Testing from %(isp)s (%(ip)s)...' % config['client'])
  File "/usr/local/lib/python2.7/dist-packages/speedtest_cli.py", line 146, in print_
    write(arg)
  File "/usr/local/lib/python2.7/dist-packages/speedtest_cli.py", line 111, in write
    fp.write(data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 20-21: ordinal not in range(128)
Warning: empty y range [0:0], adjusting to [-1:1]

But if i run speedtest-cli directly, all works

**Comment by fernandobayit** [comment]
Solution by Bruno Emanuel Silva

In file "/usr/local/bin/speedtest-cli"
add line 
reload(sys)
sys.setdefaultencoding('utf-8')

this error may appear in some dist. as it is a speedtes-cli project error will not be corrected here.
